---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: proj-scoutid-dev
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgBEa4C+wJgDQLEQgiPue7dNlskmE9BWzF+86TI4MTtaMoDqpkw04IfpK5g2hp92VcsalXD/3RNOYn6Ua6jM8oO/QxhvgpWlcLvBCtJCsconw6cILgflCIZBOKSB/aDJ9YQf5ROfou4uDLE38wk3G313zW04BKQ3/pu4d2QduVpBEAm3D8BZzZuYBRFOiWCIL8dId+Ma/GjDC1QblUoRkPViTRoY/SqaNZA4yv4QTtM7//dfgIVVS5a+9/qT/8AZARLVNuuXr114UsQa3QznIKMuOngRF51BRjSE5xcWA/H9sCHCVWFpYY3qNHrbzkphN88rbvGMbgiOSOF1muy769RAExd4TahOyAXgNt+GcDsL51tx3pe7gKTnO4tmHwl9u40IFEDQGI72RFOw3GJ+QFwABhHmAT3dakZyUhCPMgXOFOzDCYCqo93K5XbsSuC12mmdJz6WknJ1GbvtvXqy47GYxvBLRBeXhz4ce2id00NPSTsx6dNQ40Sqhpt85A1pUNN8pZCeDZyv50dFC7wzLfywBKJFPw7+qdEazNPNOMPIX3ZrqflH+voDT5M32J+QRtYn14bO8v8A5aHlEFBDkuJHoCcp+UOBBOwW+xJ0UIx52D6X3agx3lU+9+N8p8S7v+R/vpziQnRluUgaUghT41nlvJ9ep236Hw2GaK6Sg/NQLlv1aUzQpUCWMFaO5ilIIzPmYCFfIN/kDo8zio/B5KcTvkNcmb4BEGQ=
    KC_BOOTSTRAP_ADMIN_USERNAME: AgBjM0HcXfOm3tCp5rH9ZvOpEXCVLvR4qZIhn7gebdSoJiQ74f2yjPHBVCzEz3mhZ8LawBP/yLfdbgbbmgHrxB8RNJvX56CkcRv3UVc4gVqSk0ZzgStZW//LqOEIvKUHcJD4CwwzP8EdUDknwHXS7NZydHLTJlfo2HSyHd/qC2faY1DXy5nV0FUPbB8/NaYIQcDjXCqd/lumC+mRe7YPyW1uENtuHfR/pedXp1HlLvXrgev2RqaCxuYv4fQZeBbPTOLjzcMibka3V54aiqs3s5SVR7R3baW95VJUmlncAOCQpmjPn8tnYM/Jlf9dbhnLzK4TEZCAh99AXLPUsV9zCi4x28eNM0cVdJ04d5OUtCWsGHUXa5aDeFXFOV9gsFvJ52wdDe6ywhz3VSin6Adw8+CQVCyo9KJK27e2Wy1uEHKOxFUwi/2l+Fo6cA0RWdIVUPkeTZXsqGKCuxI8ehye6gDSsdQ9I90Fv/W18S3UPITnWgIQ7jOK7V5d8tLyu0LsShG9B87032lCpfdT1lkSC9Pd80ZtkRmt7X6XE4pEl4ialNHMlp72htDaE5T7JMgP56ObGyMNYyk9YYQEI82tTmN07KxUNDUP2opa1MVG+SiHntwhhZDdxvmPiyIcGKzY/mxVrkHKxQzv/tasi6GxzygbaITgoFmvcRpRQK8a53p5VVk1+4dtXzs9jHS1bR0NPN54R4tfnQ==
  template:
    metadata:
      name: keycloak-admin
      namespace: proj-scoutid-dev
