replicaCount: 1

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-ingress-class: traefik
  hosts:
    - host: headlamp.wsv2test.j26.se
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.wsv2test.j26.se

serviceAccount:
  create: true
  automountServiceAccountToken: true

rbac:
  create: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi
