#!/usr/bin/env bash
# Generate a project's database manifests, with passwords SEALED into git.
#
# Why this exists: onboarding a project used to require `az keyvault secret set`,
# so it needed an Azure/Entra account. Only one person held Key Vault Secrets
# Officer. Sealing the password instead means onboarding needs a GitHub account
# and cluster access (which the infra team already has via Dex), and nothing else.
# Key Vault stays the store for INSTALL-time infra secrets. docs/decisions.md.
#
# One password per environment is generated here and written into BOTH files that
# need it — they must not drift:
#   k8s/infra-manifest/postgres/databases/<project>.yaml   role + database (infra)
#   k8s/projects/<project>/infra/database.yaml             connection Secret
#
# Passwords are held in shell variables only. Nothing plaintext touches disk.
#
# Usage:
#   scripts/new-project-db.sh <project> <env> [<env>...]
#   scripts/new-project-db.sh proj-wsj27 dev staging prod
#
# Options:
#   --cert FILE   seal against a certificate file instead of the live cluster
#                 (the sealing key is durable, so the cert is stable)
#   --force       overwrite existing files — this ROTATES the passwords
set -euo pipefail

CERT=""
FORCE=0
ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --cert)  CERT="${2:-}"; shift 2 ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,/^set /p' "$0" | sed '$d'; exit 0 ;;
    -*) echo "unknown option: $1" >&2; exit 2 ;;
    *)  ARGS+=("$1"); shift ;;
  esac
done

if (( ${#ARGS[@]} < 2 )); then
  echo "usage: $0 [--cert FILE] [--force] <project> <env> [<env>...]" >&2
  exit 2
fi
PROJECT="${ARGS[0]}"
ENVS=("${ARGS[@]:1}")

# Same rule as docs/onboarding.md §A1: the name becomes database roles and Azure
# blob container names, and Azure rejects consecutive hyphens.
if ! [[ "$PROJECT" =~ ^[a-z0-9]([a-z0-9]|-[a-z0-9])*$ ]] || (( ${#PROJECT} > 58 )); then
  echo "invalid project name: $PROJECT" >&2
  echo "lowercase alphanumeric and SINGLE hyphens, start/end alphanumeric, <=58 chars" >&2
  exit 2
fi

cd "$(git rev-parse --show-toplevel)"
INFRA_FILE="k8s/infra-manifest/postgres/databases/$PROJECT.yaml"
PROJ_FILE="k8s/projects/$PROJECT/infra/database.yaml"

if [[ ! -d "k8s/projects/$PROJECT/infra" ]]; then
  echo "no such project directory: k8s/projects/$PROJECT/infra" >&2
  echo "run docs/onboarding.md section A first" >&2
  exit 2
fi

# Re-running generates NEW passwords. On a live database that rotates the role
# out from under whatever is connected, so make it deliberate.
if (( ! FORCE )); then
  for f in "$INFRA_FILE" "$PROJ_FILE"; do
    if [[ -e "$f" ]]; then
      echo "refusing to overwrite $f" >&2
      echo "pass --force to rotate the passwords for every listed environment" >&2
      exit 1
    fi
  done
fi

SEAL=(kubeseal --format yaml --scope strict)
FETCH=(kubeseal --fetch-cert)
if [[ -n "$CERT" ]]; then
  SEAL+=(--cert "$CERT")
  FETCH=(cat "$CERT")
else
  for a in --controller-namespace sealed-secrets --controller-name sealed-secrets-controller; do
    SEAL+=("$a"); FETCH+=("$a")
  done
fi

# Fail early and clearly rather than writing half a file.
if ! "${FETCH[@]}" >/dev/null 2>&1; then
  echo "cannot reach the sealed-secrets controller (or read --cert)." >&2
  echo "check KUBECONFIG, or pass --cert with the durable certificate." >&2
  exit 1
fi

HOST="shared-rw.postgres.svc.cluster.local"
PORT="5432"

# Generate every password up front, in memory, so both files get the same values.
declare -A PW
for env in "${ENVS[@]}"; do
  # Alphanumeric only: the password is embedded UNENCODED in the connection uri,
  # where a reserved character (@ : / % #) would break it.
  PW["$env"]="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
done

seal_secret() {   # name namespace type key=value...
  local name="$1" ns="$2" type="$3"; shift 3
  local args=()
  local kv
  for kv in "$@"; do args+=(--from-literal="$kv"); done
  kubectl create secret generic "$name" -n "$ns" --type="$type" \
    "${args[@]}" --dry-run=client -o yaml | "${SEAL[@]}"
}

# No leading `---`: kubeseal emits its own document separator, and the CNPG
# heredocs below carry theirs. Two in a row makes an empty document.
banner() { printf -- '# ---------- %s ----------\n' "$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')"; }

{
  cat <<EOF
# $PROJECT's databases on the SHARED Postgres server.
#
# GENERATED by scripts/new-project-db.sh — do not hand-edit the sealed values.
# To add an environment or rotate a password, re-run the script.
#
# Environments: ${ENVS[*]}
#
# The role password is a SealedSecret, not a Key Vault reference: onboarding a
# project must not require an Azure account. It decrypts only in this cluster and
# only as postgres/postgres-$PROJECT-<env>-role.
#
# WHY THIS LIVES HERE AND NOT IN k8s/projects/$PROJECT/infra/:
# CNPG's Database and DatabaseRole reference their Cluster by NAME ONLY
# (spec.cluster has no namespace field), so both must live in the shared
# cluster's namespace. Keeping them infra-owned also means a project cannot
# create objects next to another project's database.
EOF
  for env in "${ENVS[@]}"; do
    banner "$env"
    # CNPG *consumes* this Secret; it does not generate one. basic-auth required.
    seal_secret "postgres-$PROJECT-$env-role" postgres kubernetes.io/basic-auth \
      "username=$PROJECT-$env" "password=${PW[$env]}"
    cat <<EOF
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: $PROJECT-$env
  namespace: postgres
spec:
  cluster:
    name: shared
  ensure: present
  name: $PROJECT-$env
  login: true
  passwordSecret:
    name: postgres-$PROJECT-$env-role
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: $PROJECT-$env
  namespace: postgres
spec:
  cluster:
    name: shared
  ensure: present
  name: $PROJECT-$env
  owner: $PROJECT-$env
  # retain: dropping the Database resource must not drop the project's data.
  databaseReclaimPolicy: retain
EOF
  done
} > "$INFRA_FILE"

{
  cat <<EOF
# Connection details for $PROJECT's databases on the SHARED Postgres server.
#
# GENERATED by scripts/new-project-db.sh — do not hand-edit the sealed values.
# The passwords here are the SAME ones written into
# k8s/infra-manifest/postgres/databases/$PROJECT.yaml; regenerate both together.
#
# Environments: ${ENVS[*]}
#
# Each namespace gets a Secret named $PROJECT-db with host, port, dbname,
# username, password and a ready-made uri. Every field is sealed, because uri
# embeds the password and the rest are not worth a second mechanism.
#
# A project that needs its OWN Postgres instance instead (heavy load, a different
# major version, an extension the shared server does not carry) can create a CNPG
# Cluster in this namespace — see docs/postgres.md.
EOF
  for env in "${ENVS[@]}"; do
    banner "$env"
    seal_secret "$PROJECT-db" "$PROJECT-$env" Opaque \
      "host=$HOST" "port=$PORT" "dbname=$PROJECT-$env" "username=$PROJECT-$env" \
      "password=${PW[$env]}" \
      "uri=postgresql://$PROJECT-$env:${PW[$env]}@$HOST:$PORT/$PROJECT-$env"
  done
} > "$PROJ_FILE"

echo "wrote $INFRA_FILE"
echo "wrote $PROJ_FILE"
echo
echo "Environments: ${ENVS[*]}"
echo "Next: label each namespace for the secret store, then commit — docs/onboarding.md."
