# Prod namespace for the project. Rename PROJECT to the project's name.
apiVersion: v1
kind: Namespace
metadata:
  name: PROJECT-prod
  labels:
    scouterna.se/project: PROJECT
    scouterna.se/env: prod
